import Foundation
import AppKit

actor AppIdentifierService {
    
    // MARK: - Cached Results
    
    private var cache: [String: CachedResult] = [:]
    
    struct CachedResult {
        let appName: String?
        let bundleID: String?
        let timestamp: Date
        let confidence: Confidence
        
        enum Confidence {
            case high
            case medium
            case low
        }
        
        var isExpired: Bool {
            Date().timeIntervalSince(timestamp) > 7 * 24 * 60 * 60
        }
    }
    
    // MARK: - Public API
    
    func identifyApp(
        itemName: String,
        bundleIDHint: String? = nil
    ) async -> (appName: String?, bundleID: String?, confidence: CachedResult.Confidence) {
        
        let cleanName = cleanItemName(itemName)
        
        if let cached = cache[cleanName], !cached.isExpired {
            return (cached.appName, cached.bundleID, cached.confidence)
        }
        
        if let bundleIDHint = bundleIDHint {
            if let result = await searchByBundleID(bundleIDHint) {
                cacheResult(for: cleanName, result: result)
                return (result.appName, result.bundleID, result.confidence)
            }
        }
        
        if let result = await searchByName(cleanName) {
            cacheResult(for: cleanName, result: result)
            return (result.appName, result.bundleID, result.confidence)
        }
        
        let emptyResult = CachedResult(
            appName: nil,
            bundleID: nil,
            timestamp: Date(),
            confidence: .low
        )
        cacheResult(for: cleanName, result: emptyResult)
        return (nil, nil, .low)
    }
    
    // MARK: - Search Methods
    
    private func searchByBundleID(_ bundleID: String) async -> CachedResult? {
        if let localResult = searchLocalLaunchServices(bundleID: bundleID) {
            return localResult
        }
        
        let bundleComponents = bundleID.components(separatedBy: ".")
        
        let cleanComponents = bundleComponents.filter { component in
            !["com", "org", "net", "io", "app", "de", "fr", "uk", "us", "co"].contains(component.lowercased())
        }
        
        for component in cleanComponents {
            if let heuristicResult = applyHeuristics(component) {
                return heuristicResult
            }
        }
        
        if let lastComponent = cleanComponents.last, lastComponent.count >= 3 {
            return CachedResult(
                appName: lastComponent.capitalized,
                bundleID: bundleID,
                timestamp: Date(),
                confidence: .low
            )
        }
        
        return nil
    }
    
    private func searchByName(_ name: String) async -> CachedResult? {
        if let heuristicResult = applyHeuristics(name) {
            return heuristicResult
        }
        
        if let knownPattern = matchKnownPatterns(name) {
            return knownPattern
        }
        
        return nil
    }
    
    // MARK: - Local Search
    
    private func searchLocalLaunchServices(bundleID: String) -> CachedResult? {
        let workspace = NSWorkspace.shared
        
        if let appURL = workspace.urlForApplication(withBundleIdentifier: bundleID) {
            let appName = appURL.deletingPathExtension().lastPathComponent
            return CachedResult(
                appName: appName,
                bundleID: bundleID,
                timestamp: Date(),
                confidence: .high
            )
        }
        
        return nil
    }
    
    // MARK: - Heuristics
    
    private func applyHeuristics(_ name: String) -> CachedResult? {
        let nameLower = name.lowercased()
        
        let patterns: [(pattern: String, appName: String, bundleID: String)] = [
            ("adobe", "Adobe Creative Cloud", "com.adobe.creative-cloud"),
            ("creative cloud", "Adobe Creative Cloud", "com.adobe.creative-cloud"),
            ("cc desktop", "Adobe Creative Cloud", "com.adobe.acc.AdobeDesktopService"),
            ("adobe desktop service", "Adobe Desktop Service", "com.adobe.acc.AdobeDesktopService"),
            ("adobe crash reporter", "Adobe Crash Reporter", "com.adobe.CrashReporter"),
            ("adobe sync", "Adobe Creative Cloud Sync", "com.adobe.AdobeCreativeCloudSync"),
            ("photoshop", "Adobe Photoshop", "com.adobe.Photoshop"),
            ("illustrator", "Adobe Illustrator", "com.adobe.Illustrator"),
            ("indesign", "Adobe InDesign", "com.adobe.InDesign"),
            ("acrobat", "Adobe Acrobat", "com.adobe.Acrobat"),
            ("acrobat pro", "Adobe Acrobat Pro", "com.adobe.Acrobat.Pro"),
            ("acrobat reader", "Adobe Acrobat Reader", "com.adobe.Reader"),
            ("premiere", "Adobe Premiere Pro", "com.adobe.PremierePro"),
            ("premiere pro", "Adobe Premiere Pro", "com.adobe.PremierePro"),
            ("after effects", "Adobe After Effects", "com.adobe.AfterEffects"),
            ("aftereffects", "Adobe After Effects", "com.adobe.AfterEffects"),
            ("media encoder", "Adobe Media Encoder", "com.adobe.ame.application"),
            ("prelude", "Adobe Prelude", "com.adobe.Prelude"),
            ("character animator", "Adobe Character Animator", "com.adobe.CharacterAnimator"),
            ("animate", "Adobe Animate", "com.adobe.Animate"),
            ("lightroom", "Adobe Lightroom", "com.adobe.Lightroom"),
            ("lightroom classic", "Adobe Lightroom Classic", "com.adobe.LightroomClassic7"),
            ("camera raw", "Adobe Camera Raw", "com.adobe.CameraRaw"),
            ("bridge", "Adobe Bridge", "com.adobe.bridge"),
            ("dreamweaver", "Adobe Dreamweaver", "com.adobe.Dreamweaver"),
            ("xd", "Adobe XD", "com.adobe.xd"),
            ("muse", "Adobe Muse", "com.adobe.muse"),
            ("audition", "Adobe Audition", "com.adobe.Audition"),
            ("dimension", "Adobe Dimension", "com.adobe.dimension"),
            ("substance 3d painter", "Adobe Substance 3D Painter", "com.adobe.Substance3DPainter"),
            ("substance 3d designer", "Adobe Substance 3D Designer", "com.adobe.Substance3DDesigner"),
            ("substance 3d sampler", "Adobe Substance 3D Sampler", "com.adobe.Substance3DSampler"),
            ("substance 3d stager", "Adobe Substance 3D Stager", "com.adobe.Substance3DStager"),
            ("aero", "Adobe Aero", "com.adobe.Aero"),
            ("adobe express", "Adobe Express", "com.adobe.express"),
            ("spark", "Adobe Spark", "com.adobe.CreativeApps.Spark"),
            ("stock", "Adobe Stock", "com.adobe.stock"),
            ("fresco", "Adobe Fresco", "com.adobe.fresco"),
            ("premiere rush", "Adobe Premiere Rush", "com.adobe.PremierRush"),
            ("incopy", "Adobe InCopy", "com.adobe.InCopy"),
            ("captivate", "Adobe Captivate", "com.adobe.Captivate"),
            ("adobe fonts", "Adobe Fonts", "com.adobe.ACC.AdobeFonts"),
            ("typekit", "Adobe Fonts", "com.adobe.typekit"),
            ("extension manager", "Adobe Extension Manager", "com.adobe.ExtensionManager"),
            ("adobe application manager", "Adobe Application Manager", "com.adobe.aam"),
            ("adobe installer", "Adobe Installer", "com.adobe.Installers.Setup"),
            ("adobe air", "Adobe AIR", "com.adobe.air"),
            ("flash", "Adobe Flash", "com.adobe.Flash"),
            ("flash player", "Adobe Flash Player", "com.adobe.flashplayer"),
            ("adobe genuine service", "Adobe Genuine Service", "com.adobe.AdobeGenuineService"),
            ("ipc broker", "Adobe IPC Broker", "com.adobe.acc.IPCBroker"),
            ("cef helper", "Adobe CEF Helper", "com.adobe.cef"),
            ("core sync", "Adobe Core Sync", "com.adobe.coresync"),
            ("cc library", "Adobe CC Library", "com.adobe.CCLibrary"),
            ("collaboration sync", "Adobe Collaboration Sync", "com.adobe.CollaborationSyncApp"),
            ("microsoft", "Microsoft", "com.microsoft"),
            ("onedrive", "OneDrive", "com.microsoft.OneDrive"),
            ("com.microsoft.onedrive", "OneDrive", "com.microsoft.OneDrive"),
            ("teams", "Microsoft Teams", "com.microsoft.teams"),
            ("outlook", "Microsoft Outlook", "com.microsoft.Outlook"),
            ("word", "Microsoft Word", "com.microsoft.Word"),
            ("excel", "Microsoft Excel", "com.microsoft.Excel"),
            ("powerpoint", "Microsoft PowerPoint", "com.microsoft.Powerpoint"),
            ("onenote", "Microsoft OneNote", "com.microsoft.onenote.mac"),
            ("edge", "Microsoft Edge", "com.microsoft.edgemac"),
            ("todo", "Microsoft To Do", "com.microsoft.to-do"),
            ("remote desktop", "Microsoft Remote Desktop", "com.microsoft.rdc.macos"),
            ("microsoft defender", "Microsoft Defender", "com.microsoft"),
            ("defender for endpoint", "Microsoft Defender for Endpoint", "com.microsoft"),
            ("company portal", "Microsoft Company Portal", "com.microsoft"),
            ("intune company portal", "Microsoft Company Portal", "com.microsoft"),
            ("microsoft autoupdate", "Microsoft AutoUpdate", "com.microsoft"),
            ("microsoft auto update", "Microsoft AutoUpdate", "com.microsoft"),
            ("microsoft update assistant", "Microsoft AutoUpdate", "com.microsoft"),
            ("google", "Google", "com.google"),
            ("chrome", "Google Chrome", "com.google.Chrome"),
            ("drive", "Google Drive", "com.google.GoogleDrive"),
            ("backup and sync", "Backup and Sync", "com.google.GoogleDrive"),
            ("xcode", "Xcode", "com.apple.dt.Xcode"),
            ("instruments", "Instruments", "com.apple.dt.Instruments"),
            ("simulator", "Simulator", "com.apple.iphonesimulator"),
            ("reality composer", "Reality Composer", "com.apple.RealityComposer"),
            ("reality converter", "Reality Converter", "com.apple.RealityConverter"),
            ("create ml", "Create ML", "com.apple.CreateML"),
            ("accessibility inspector", "Accessibility Inspector", "com.apple.AccessibilityInspector"),
            ("network link conditioner", "Network Link Conditioner", "com.apple.NetworkLinkConditioner"),
            ("package", "Package", "com.apple.dt.PackageApplication"),
            ("group.com.apple", "Apple", "com.apple"),
            ("finder", "Finder", "com.apple.finder"),
            ("safari", "Safari", "com.apple.Safari"),
            ("mail", "Mail", "com.apple.mail"),
            ("contacts", "Contacts", "com.apple.AddressBook"),
            ("calendar", "Calendar", "com.apple.iCal"),
            ("reminders", "Reminders", "com.apple.reminders"),
            ("notes", "Notes", "com.apple.Notes"),
            ("messages", "Messages", "com.apple.MobileSMS"),
            ("imessage", "Messages", "com.apple.iChat"),
            ("facetime", "FaceTime", "com.apple.FaceTime"),
            ("photos", "Photos", "com.apple.Photos"),
            ("photo booth", "Photo Booth", "com.apple.PhotoBooth"),
            ("preview", "Preview", "com.apple.Preview"),
            ("quicktime", "QuickTime Player", "com.apple.QuickTimePlayerX"),
            ("music", "Music", "com.apple.Music"),
            ("apple music", "Music", "com.apple.Music"),
            ("itunes", "iTunes", "com.apple.iTunes"),
            ("tv", "TV", "com.apple.TV"),
            ("apple tv", "TV", "com.apple.TV"),
            ("podcasts", "Podcasts", "com.apple.podcasts"),
            ("news", "News", "com.apple.news"),
            ("stocks", "Stocks", "com.apple.stocks"),
            ("home", "Home", "com.apple.Home"),
            ("shortcuts", "Shortcuts", "com.apple.shortcuts"),
            ("voice memos", "Voice Memos", "com.apple.VoiceMemos"),
            ("books", "Books", "com.apple.iBooksX"),
            ("app store", "App Store", "com.apple.AppStore"),
            ("maps", "Maps", "com.apple.Maps"),
            ("find my", "Find My", "com.apple.findmy"),
            ("freeform", "Freeform", "com.apple.freeform"),
            ("clock", "Clock", "com.apple.clock"),
            ("weather", "Weather", "com.apple.weather"),
            ("translate", "Translate", "com.apple.Translate"),
            ("pages", "Pages", "com.apple.iWork.Pages"),
            ("numbers", "Numbers", "com.apple.iWork.Numbers"),
            ("keynote", "Keynote", "com.apple.iWork.Keynote"),
            ("final cut pro", "Final Cut Pro", "com.apple.FinalCut"),
            ("finalcut", "Final Cut Pro", "com.apple.FinalCut"),
            ("logic pro", "Logic Pro", "com.apple.logic10"),
            ("logic", "Logic Pro", "com.apple.logic10"),
            ("mainstage", "MainStage", "com.apple.mainstage3"),
            ("motion", "Motion", "com.apple.motionapp"),
            ("compressor", "Compressor", "com.apple.Compressor"),
            ("garageband", "GarageBand", "com.apple.garageband10"),
            ("activity monitor", "Activity Monitor", "com.apple.ActivityMonitor"),
            ("airport utility", "AirPort Utility", "com.apple.AirPortUtility"),
            ("audio midi setup", "Audio MIDI Setup", "com.apple.audio.AudioMIDISetup"),
            ("bluetooth file exchange", "Bluetooth File Exchange", "com.apple.BluetoothFileExchange"),
            ("boot camp assistant", "Boot Camp Assistant", "com.apple.BootCampAssistant"),
            ("calculator", "Calculator", "com.apple.calculator"),
            ("colorsnc utility", "ColorSync Utility", "com.apple.ColorSyncUtility"),
            ("console", "Console", "com.apple.Console"),
            ("digital color meter", "Digital Color Meter", "com.apple.DigitalColorMeter"),
            ("disk utility", "Disk Utility", "com.apple.DiskUtility"),
            ("font book", "Font Book", "com.apple.FontBook"),
            ("fontbook", "Font Book", "com.apple.FontBook"),
            ("grapher", "Grapher", "com.apple.grapher"),
            ("keychain access", "Keychain Access", "com.apple.keychainaccess"),
            ("migration assistant", "Migration Assistant", "com.apple.MigrationAssistant"),
            ("script editor", "Script Editor", "com.apple.ScriptEditor2"),
            ("system information", "System Information", "com.apple.SystemProfiler"),
            ("terminal", "Terminal", "com.apple.Terminal"),
            ("voiceover utility", "VoiceOver Utility", "com.apple.VoiceOverUtility"),
            ("screenshot", "Screenshot", "com.apple.screencaptureui"),
            ("system preferences", "System Preferences", "com.apple.systempreferences"),
            ("system settings", "System Settings", "com.apple.SystemPreferences"),
            ("time machine", "Time Machine", "com.apple.backup.launcher"),
            ("timemachine", "Time Machine", "com.apple.TimeMachine"),
            ("icloud", "iCloud", "com.apple.iCloud"),
            ("icloud drive", "iCloud Drive", "com.apple.iCloudDrive"),
            ("automator", "Automator", "com.apple.Automator"),
            ("applescript editor", "Script Editor", "com.apple.ScriptEditor2"),
            ("dictionary", "Dictionary", "com.apple.Dictionary"),
            ("chess", "Chess", "com.apple.Chess"),
            ("dvd player", "DVD Player", "com.apple.DVDPlayer"),
            ("image capture", "Image Capture", "com.apple.ImageCapture2"),
            ("stickies", "Stickies", "com.apple.Stickies"),
            ("textedit", "TextEdit", "com.apple.TextEdit"),
            ("mission control", "Mission Control", "com.apple.exposelauncher"),
            ("launchpad", "Launchpad", "com.apple.launchpad.launcher"),
            ("notification center", "Notification Center", "com.apple.notificationcenterui"),
            ("siri", "Siri", "com.apple.Siri"),
            ("spotlight", "Spotlight", "com.apple.Spotlight"),
            ("vpn", "VPN", "com.apple.NetworkUtility"),
            ("network utility", "Network Utility", "com.apple.NetworkUtility"),
            ("screen saver", "Screen Saver", "com.apple.ScreenSaver.Engine"),
            ("quicklook", "Quick Look", "com.apple.quicklook.ui.helper"),
            ("archive utility", "Archive Utility", "com.apple.archiveutility"),
            ("voiceover", "VoiceOver", "com.apple.VoiceOver"),
            ("zoom", "Zoom", "com.apple.zoom"),
            ("game center", "Game Center", "com.apple.gamecenter"),
            ("phone", "Phone", "com.apple.TelephonyUtilities"),
            ("wallet", "Wallet", "com.apple.Passbook"),
            ("health", "Health", "com.apple.Health"),
            ("fitness", "Fitness", "com.apple.Fitness"),
            ("tips", "Tips", "com.apple.tips"),
            ("measure", "Measure", "com.apple.Measure"),
            ("magnifier", "Magnifier", "com.apple.Magnifier"),
            ("journal", "Journal", "com.apple.journal"),
            ("passwords", "Passwords", "com.apple.Passwords"),
            ("accountsd", "Accounts Daemon", "com.apple.accountsd"),
            ("airplayuiagent", "AirPlay UI Agent", "com.apple.AirPlayUIAgent"),
            ("appleeventsd", "Apple Events Daemon", "com.apple.coreservices.appleeventsd"),
            ("apsd", "Apple Push Service Daemon", "com.apple.apsd"),
            ("bird", "iCloud Bird", "com.apple.bird"),
            ("cloudd", "iCloud Daemon", "com.apple.cloudd"),
            ("cloudpaird", "CloudPair Daemon", "com.apple.cloudpaird"),
            ("coreauthd", "Core Auth Daemon", "com.apple.CoreAuthentication.daemon"),
            ("corespeechd", "Core Speech Daemon", "com.apple.corespeechd"),
            ("coreservicesd", "Core Services Daemon", "com.apple.coreservicesd"),
            ("deleted", "Delete Daemon", "com.apple.deleted"),
            ("diskmanagementd", "Disk Management Daemon", "com.apple.diskmanagementd"),
            ("distnoted", "Distributed Notification Daemon", "com.apple.distnoted"),
            ("dprivacyd", "Privacy Daemon", "com.apple.dprivacyd"),
            ("familycircled", "Family Circle Daemon", "com.apple.familycircled"),
            ("findmy", "Find My", "com.apple.findmy"),
            ("fseventsd", "FS Events Daemon", "com.apple.fseventsd"),
            ("iclouddrived", "iCloud Drive Daemon", "com.apple.iCloudDriveService"),
            ("imagent", "iMessage Agent", "com.apple.imagent"),
            ("kernel_task", "Kernel Task", "com.apple.kernel"),
            ("logd", "Log Daemon", "com.apple.logd"),
            ("loginwindow", "Login Window", "com.apple.loginwindow"),
            ("lsd", "Launch Services Daemon", "com.apple.coreservices.launchservicesd"),
            ("mediaanalysisd", "Media Analysis Daemon", "com.apple.mediaanalysisd"),
            ("mediaremoted", "Media Remote Daemon", "com.apple.mediaremoted"),
            ("notifyd", "Notify Daemon", "com.apple.notifyd"),
            ("nsattributiond", "Attribution Daemon", "com.apple.NSAttributionDaemon"),
            ("parsecd", "Parse Daemon", "com.apple.parsecd"),
            ("photolibraryd", "Photo Library Daemon", "com.apple.photolibraryd"),
            ("powerchimed", "Power Chime Daemon", "com.apple.powerchimed"),
            ("rapportd", "Rapport Daemon", "com.apple.rapportd"),
            ("sharingd", "Sharing Daemon", "com.apple.sharingd"),
            ("soagent", "Significant Other Agent", "com.apple.soagent"),
            ("softwareupdated", "Software Update Daemon", "com.apple.softwareupdated"),
            ("sysmond", "System Monitor Daemon", "com.apple.sysmond"),
            ("systemstatsd", "System Stats Daemon", "com.apple.systemstatsd"),
            ("trustd", "Trust Daemon", "com.apple.trustd"),
            ("universalaccessd", "Universal Access Daemon", "com.apple.universalaccessd"),
            ("usernoted", "User Note Daemon", "com.apple.usernoted"),
            ("usernotificationsd", "User Notifications Daemon", "com.apple.usernotificationsd"),
            ("warmd", "Warm Daemon", "com.apple.warmd"),
            ("wifid", "WiFi Daemon", "com.apple.wifid"),
            ("windowserver", "Window Server", "com.apple.WindowServer"),
            ("dtservicehub", "Xcode Service Hub", "com.apple.dt.DTServiceHub"),
            ("sourcekit", "SourceKit Service", "com.apple.dt.SourceKitService"),
            ("ibtoold", "Interface Builder Tool Daemon", "com.apple.dt.ibtoold"),
            ("handoff", "Handoff", "com.apple.coreservices.handoff"),
            ("continuity", "Continuity", "com.apple.Continuity"),
            ("universal control", "Universal Control", "com.apple.UniversalControl"),
            ("sidecar", "Sidecar", "com.apple.sidecar"),
            ("intellij", "IntelliJ IDEA", "com.jetbrains.intellij"),
            ("pycharm", "PyCharm", "com.jetbrains.pycharm"),
            ("webstorm", "WebStorm", "com.jetbrains.webstorm"),
            ("phpstorm", "PhpStorm", "com.jetbrains.PhpStorm"),
            ("rubymine", "RubyMine", "com.jetbrains.rubymine"),
            ("clion", "CLion", "com.jetbrains.CLion"),
            ("goland", "GoLand", "com.jetbrains.goland"),
            ("rider", "Rider", "com.jetbrains.rider"),
            ("datagrip", "DataGrip", "com.jetbrains.datagrip"),
            ("appcode", "AppCode", "com.jetbrains.AppCode"),
            ("jetbrains", "JetBrains", "com.jetbrains"),
            ("jetbrains toolbox", "JetBrains Toolbox", "com.jetbrains.toolbox"),
            ("vscode", "Visual Studio Code", "com.microsoft.VSCode"),
            ("visual studio code", "Visual Studio Code", "com.microsoft.VSCode"),
            ("sublime", "Sublime Text", "com.sublimetext"),
            ("atom", "Atom", "com.github.atom"),
            ("brackets", "Brackets", "io.brackets.appshell"),
            ("nova", "Nova", "com.panic.Nova"),
            ("bbedit", "BBEdit", "com.barebones.bbedit"),
            ("textmate", "TextMate", "com.macromates.TextMate"),
            ("coda", "Coda", "com.panic.Coda2"),
            ("docker", "Docker", "com.docker.docker"),
            ("sourcetree", "Sourcetree", "com.torusknot.SourceTreeNotMAS"),
            ("postman", "Postman", "com.postmanlabs.mac"),
            ("insomnia", "Insomnia", "com.insomnia.app"),
            ("fork", "Fork", "com.DanPristupov.Fork"),
            ("tower", "Tower", "com.fournova.Tower3"),
            ("kaleidoscope", "Kaleidoscope", "com.blackpixel.kaleidoscope"),
            ("dash", "Dash", "com.kapeli.dashdoc"),
            ("iterm", "iTerm", "com.googlecode.iterm2"),
            ("homebrew", "Homebrew", "sh.brew.homebrew"),
            ("macports", "MacPorts", "org.macports"),
            ("oracle", "Oracle", "com.oracle"),
            ("oracle java", "Oracle Java", "com.oracle.java"),
            ("java", "Java", "com.oracle.java"),
            ("openjdk", "OpenJDK", "net.java.openjdk"),
            ("jdk", "Java Development Kit", "com.oracle.java"),
            ("com.oracle.javadeployment", "Oracle Java Deployment", "com.oracle.javadeployment"),
            ("net.java.openjdk", "OpenJDK", "net.java.openjdk"),
            ("jreinstaller", "Oracle Java", "com.oracle.java"),
            ("parallels", "Parallels Desktop", "com.parallels.desktop"),
            ("parallels desktop", "Parallels Desktop", "com.parallels.desktop.console"),
            ("parallels toolbox", "Parallels Toolbox", "com.parallels.toolbox"),
            ("parallels.toolbox", "Parallels Toolbox", "com.parallels.toolbox"),
            ("crossover", "CrossOver", "com.codeweavers.CrossOver"),
            ("com.codeweavers.crossover", "CrossOver", "com.codeweavers.CrossOver"),
            ("codeweavers", "CodeWeavers", "com.codeweavers"),
            ("parallels-alarm", "Parallels Toolbox Alarm", "com.parallels.toolbox.Alarm"),
            ("parallels-airplane", "Parallels Toolbox Airplane Mode", "com.parallels.toolbox.AirplaneMode"),
            ("parallels-archive", "Parallels Toolbox Archive", "com.parallels.toolbox.Archive"),
            ("parallels-capture-area", "Parallels Toolbox Capture Area", "com.parallels.toolbox.CaptureArea"),
            ("parallels-capture-screen", "Parallels Toolbox Capture Screen", "com.parallels.toolbox.CaptureScreen"),
            ("parallels-capture-window", "Parallels Toolbox Capture Window", "com.parallels.toolbox.CaptureWindow"),
            ("parallels-block-camera", "Parallels Toolbox Block Camera", "com.parallels.toolbox.BlockCamera"),
            ("parallels-block-microphone", "Parallels Toolbox Block Microphone", "com.parallels.toolbox.BlockMicrophone"),
            ("parallels-disable-camera", "Parallels Toolbox Block Camera", "com.parallels.toolbox.BlockCamera"),
            ("parallels-mute-microphone", "Parallels Toolbox Microphone Off", "com.parallels.toolbox.MicrophoneOff"),
            ("parallels-business-cards", "Parallels Toolbox Business Cards", "com.parallels.toolbox.BusinessCards"),
            ("parallels-clean-drive", "Parallels Toolbox Clean Drive", "com.parallels.toolbox.CleanDrive"),
            ("parallels.toolbox.cleandrive", "Parallels Toolbox Clean Drive", "com.parallels.toolbox.CleanDrive"),
            ("parallels-clipboard-history", "Parallels Toolbox Clipboard History", "com.parallels.toolbox.ClipboardHistory"),
            ("parallels-convert-audio", "Parallels Toolbox Convert Audio", "com.parallels.toolbox.ConvertAudio"),
            ("parallels-convert-video", "Parallels Toolbox Convert Video", "com.parallels.toolbox.ConvertVideo"),
            ("parallels-date-countdown", "Parallels Toolbox Date Countdown", "com.parallels.toolbox.DateCountdown"),
            ("parallels-download-audio", "Parallels Toolbox Download Audio", "com.parallels.toolbox.DownloadAudio"),
            ("parallels-download-video", "Parallels Toolbox Download Video", "com.parallels.toolbox.DownloadVideo"),
            ("parallels-do-not-disturb", "Parallels Toolbox Do Not Disturb", "com.parallels.toolbox.DoNotDisturb"),
            ("parallels-do-not-sleep", "Parallels Toolbox Do Not Sleep", "com.parallels.toolbox.DoNotSleep"),
            ("parallels-eject-volumes", "Parallels Toolbox Eject Volumes", "com.parallels.toolbox.EjectVolumes"),
            ("parallels-encrypt-files", "Parallels Toolbox Encrypt Files", "com.parallels.toolbox.EncryptFiles"),
            ("parallels-energy-saver", "Parallels Toolbox Energy Saver", "com.parallels.toolbox.EnergySaver"),
            ("parallels-find-duplicates", "Parallels Toolbox Find Duplicates", "com.parallels.toolbox.FindDuplicates"),
            ("parallels-focus-on-window", "Parallels Toolbox Focus on Window", "com.parallels.toolbox.FocusOnWindow"),
            ("parallels-free-memory", "Parallels Toolbox Free Memory", "com.parallels.toolbox.FreeMemory"),
            ("parallels-hidden-files", "Parallels Toolbox Hidden Files", "com.parallels.toolbox.HiddenFiles"),
            ("parallels-hide-desktop", "Parallels Toolbox Hide Desktop", "com.parallels.toolbox.HideDesktop"),
            ("parallels-hide-menu-icons", "Parallels Toolbox Hide Menu Icons", "com.parallels.toolbox.HideMenuIcons"),
            ("parallels-launch", "Parallels Toolbox Launch", "com.parallels.toolbox.Launch"),
            ("parallels-lock-screen", "Parallels Toolbox Lock Screen", "com.parallels.toolbox.LockScreen"),
            ("parallels-make-gif", "Parallels Toolbox Make GIF", "com.parallels.toolbox.MakeGif"),
            ("parallels-make-presentation", "Parallels Toolbox Make Presentation", "com.parallels.toolbox.MakePresentation"),
            ("parallels-microphone-off", "Parallels Toolbox Microphone Off", "com.parallels.toolbox.MicrophoneOff"),
            ("parallels-optimize-video", "Parallels Toolbox Optimize Video", "com.parallels.toolbox.OptimizeVideo"),
            ("parallels-presentation-mode", "Parallels Toolbox Presentation Mode", "com.parallels.toolbox.PresentationMode"),
            ("parallels-record-area", "Parallels Toolbox Record Area", "com.parallels.toolbox.RecordArea"),
            ("parallels-record-audio", "Parallels Toolbox Record Audio", "com.parallels.toolbox.RecordAudio"),
            ("parallels-record-screen", "Parallels Toolbox Record Screen", "com.parallels.toolbox.RecordScreen"),
            ("parallels-record-window", "Parallels Toolbox Record Window", "com.parallels.toolbox.RecordWindow"),
            ("parallels-resize-images", "Parallels Toolbox Resize Images", "com.parallels.toolbox.ResizeImages"),
            ("parallels-recognize-text", "Parallels Toolbox Recognize Text", "com.parallels.toolbox.RecognizeText"),
            ("parallels-screenshot", "Parallels Toolbox Screenshot", "com.parallels.toolbox.Screenshot"),
            ("parallels-screenshot-page", "Parallels Toolbox Screenshot Page", "com.parallels.toolbox.ScreenshotPage"),
            ("parallels-stopwatch", "Parallels Toolbox Stopwatch", "com.parallels.toolbox.Stopwatch"),
            ("parallels-switch-resolution", "Parallels Toolbox Switch Resolution", "com.parallels.toolbox.SwitchResolution"),
            ("parallels-take-break", "Parallels Toolbox Take a Break", "com.parallels.toolbox.TakeBreak"),
            ("parallels-take-photo", "Parallels Toolbox Take Photo", "com.parallels.toolbox.TakePhoto"),
            ("parallels-take-video", "Parallels Toolbox Take Video", "com.parallels.toolbox.TakeVideo"),
            ("parallels-timer", "Parallels Toolbox Timer", "com.parallels.toolbox.Timer"),
            ("parallels-unarchive", "Parallels Toolbox Unarchive", "com.parallels.toolbox.Unarchive"),
            ("parallels-unit-converter", "Parallels Toolbox Unit Converter", "com.parallels.toolbox.UnitConverter"),
            ("parallels-world-time", "Parallels Toolbox World Time", "com.parallels.toolbox.WorldTime"),
            ("parallels access", "Parallels Access", "com.parallels.access.mac"),
            ("parallels client", "Parallels Client", "com.parallels.winapp"),
            ("vmware", "VMware Fusion", "com.vmware.fusion"),
            ("vmware fusion", "VMware Fusion", "com.vmware.fusion"),
            ("vmware horizon", "VMware Horizon Client", "com.vmware.horizon"),
            ("virtualbox", "VirtualBox", "org.virtualbox.app.VirtualBox"),
            ("vagrant", "Vagrant", "com.vagrant.vagrant"),
            ("qemu", "QEMU", "org.qemu"),
            ("utm app", "UTM", "com.utmapp.UTM"),
            ("utmapp", "UTM", "com.utmapp.UTM"),
            ("com.utmapp", "UTM", "com.utmapp.UTM"),
            ("slack", "Slack", "com.tinyspeck.slackmacgap"),
            ("discord", "Discord", "com.hnc.Discord"),
            ("zoom", "Zoom", "us.zoom.xos"),
            ("skype", "Skype", "com.skype.skype"),
            ("telegram", "Telegram", "ru.keepcoder.Telegram"),
            ("whatsapp", "WhatsApp", "net.whatsapp.WhatsApp"),
            ("signal", "Signal", "org.whispersystems.signal-desktop"),
            ("element", "Element", "im.riot.app"),
            ("teamviewer", "TeamViewer", "com.teamviewer.TeamViewer"),
            ("anydesk", "AnyDesk", "com.philandro.anydesk"),
            ("facebook", "Facebook", "com.facebook"),
            ("notion", "Notion", "notion.id"),
            ("evernote", "Evernote", "com.evernote.Evernote"),
            ("onenote", "OneNote", "com.microsoft.onenote.mac"),
            ("bear", "Bear", "net.shinyfrog.bear"),
            ("ulysses", "Ulysses", "com.ulyssesapp.mac"),
            ("obsidian", "Obsidian", "md.obsidian"),
            ("logseq", "Logseq", "com.logseq.logseq"),
            ("craft", "Craft", "com.lukilabs.lukiapp"),
            ("dropbox", "Dropbox", "com.getdropbox.Dropbox"),
            ("box", "Box", "com.box.desktop"),
            ("sync", "Sync.com", "com.sync.desktop"),
            ("mega", "MEGA", "nz.mega.mac"),
            ("nextcloud", "Nextcloud", "com.nextcloud.desktopclient"),
            ("owncloud", "ownCloud", "com.owncloud.desktopclient"),
            ("icloud", "iCloud", "com.apple.iCloud"),
            ("cyberduck", "Cyberduck", "ch.sudo.cyberduck"),
            ("1password", "1Password", "com.agilebits.onepassword7"),
            ("lastpass", "LastPass", "com.lastpass.LastPass"),
            ("dashlane", "Dashlane", "com.dashlane.dashlanephonefinal"),
            ("bitwarden", "Bitwarden", "com.bitwarden.desktop"),
            ("keepass", "KeePassXC", "org.keepassxc.keepassxc"),
            ("enpass", "Enpass", "in.sinew.Enpass-Desktop"),
            ("spotify", "Spotify", "com.spotify.client"),
            ("vlc", "VLC", "org.videolan.vlc"),
            ("handbrake", "HandBrake", "fr.handbrake.HandBrake"),
            ("mkvmerge", "MKVToolNix", "org.bunkus.mkvtoolnix"),
            ("mkv toolnix", "MKVToolNix", "org.bunkus.mkvtoolnix"),
            ("plex", "Plex", "tv.plex.desktop"),
            ("obs", "OBS Studio", "com.obsproject.obs-studio"),
            ("prism live studio", "PRISM Live Studio", "com.prismlive.prismlivestudio"),
            ("prismlive", "PRISM Live Studio", "com.prismlive.prismlivestudio"),
            ("com.prismlive.prismlivestudio", "PRISM Live Studio", "com.prismlive.prismlivestudio"),
            ("colorfinale", "Color Finale", "com.colorfinale"),
            ("lut manager", "Color Finale LUT Manager", "com.colorfinale.lutmanager"),
            ("com.colorfinale.lutmanager", "Color Finale LUT Manager", "com.colorfinale.lutmanager"),
            ("imovie", "iMovie", "com.apple.iMovieApp"),
            ("iridient", "Iridient Developer", "com.iridient.IridientDeveloper"),
            ("irident", "Iridient Developer", "com.iridient.IridientDeveloper"),
            ("x-rite", "X-Rite", "com.xrite"),
            ("xrite", "X-Rite", "com.xrite"),
            ("nch software", "NCH Software", "com.nchsoftware"),
            ("nch", "NCH Software", "com.nchsoftware"),
            ("roxio", "Roxio", "com.roxio"),
            ("recoverit", "Wondershare Recoverit", "com.wondershare.recoverit"),
            ("wondershare", "Wondershare", "com.wondershare"),
            ("iskysoft", "iSkysoft", "com.iskysoft"),
            ("roxio toast", "Roxio Toast", "com.roxio.Toast"),
            ("toast titanium", "Roxio Toast Titanium", "com.roxio.Toast"),
            ("toast", "Roxio Toast", "com.roxio.Toast"),
            ("fxfactory", "FxFactory", "com.noiseindustries.fxfactory"),
            ("noiseindustries", "Noise Industries", "com.noiseindustries"),
            ("noise industries", "Noise Industries", "com.noiseindustries"),
            ("red giant", "Red Giant", "com.redgiant"),
            ("redgiant", "Red Giant", "com.redgiant"),
            ("blackmagic", "Blackmagic", "com.blackmagic-design"),
            ("davinci resolve", "DaVinci Resolve", "com.blackmagic-design.DaVinciResolve"),
            ("davinci", "DaVinci Resolve", "com.blackmagic-design.DaVinciResolve"),
            ("davinci resolve studio", "DaVinci Resolve Studio", "com.blackmagic-design.DaVinciResolveStudio"),
            ("fusion", "Blackmagic Fusion", "com.blackmagic-design.Fusion"),
            ("fusion studio", "Blackmagic Fusion Studio", "com.blackmagic-design.FusionStudio"),
            ("blackmagic camera", "Blackmagic Camera", "com.blackmagic-design.BlackmagicCamera"),
            ("blackmagic disk speed test", "Blackmagic Disk Speed Test", "com.blackmagic-design.DiskSpeedTest"),
            ("blackmagic raw", "Blackmagic RAW", "com.blackmagic-design.BlackmagicRAW"),
            ("blackmagic raw player", "Blackmagic RAW Player", "com.blackmagic-design.BlackmagicRAWPlayer"),
            ("blackmagic raw speed test", "Blackmagic RAW Speed Test", "com.blackmagic-design.BlackmagicRAWSpeedTest"),
            ("atem software control", "ATEM Software Control", "com.blackmagic-design.ATEMSoftwareControl"),
            ("desktop video setup", "Desktop Video Setup", "com.blackmagic-design.DesktopVideoSetup"),
            ("ultrastudio", "UltraStudio", "com.blackmagic-design.UltraStudio"),
            ("hyperdeck", "HyperDeck", "com.blackmagic-design.HyperDeck"),
            ("teranex", "Teranex", "com.blackmagic-design.Teranex"),
            ("videohub", "Videohub", "com.blackmagic-design.Videohub"),
            ("smartview", "SmartView", "com.blackmagic-design.SmartView"),
            ("smartscope", "SmartScope", "com.blackmagic-design.SmartScope"),
            ("converters", "Blackmagic Converters", "com.blackmagic-design.Converters"),
            ("livestream studio", "Blackmagic Livestream Studio", "com.blackmagic-design.LivestreamStudio"),
            ("ableton", "Ableton Live", "com.ableton.live"),
            ("pro tools", "Pro Tools", "com.avid.ProTools"),
            ("audacity", "Audacity", "org.audacityteam.audacity"),
            ("reaper", "REAPER", "com.cockos.reaper"),
            ("sketch", "Sketch", "com.bohemiancoding.sketch3"),
            ("figma", "Figma", "com.figma.Desktop"),
            ("affinity designer", "Affinity Designer", "com.seriflabs.affinitydesigner"),
            ("affinity photo", "Affinity Photo", "com.seriflabs.affinityphoto"),
            ("affinity publisher", "Affinity Publisher", "com.seriflabs.affinitypublisher"),
            ("pixelmator", "Pixelmator Pro", "com.pixelmatorteam.pixelmator.x"),
            ("acorn", "Acorn", "com.flyingmeat.Acorn7"),
            ("procreate", "Procreate", "com.savageinteractive.procreate"),
            ("blender", "Blender", "org.blenderfoundation.blender"),
            ("cinema4d", "Cinema 4D", "net.maxon.cinema4d"),
            ("maxon", "Maxon", "net.maxon"),
            ("redshift", "Redshift", "com.redshift3d"),
            ("redshift3d", "Redshift", "com.redshift3d"),
            ("zbrush", "ZBrush", "com.pixologic.zbrush"),
            ("maya", "Maya", "com.autodesk.maya"),
            ("zbrush", "ZBrush", "com.pixologic.zbrush"),
            ("alfred", "Alfred", "com.runningwithcrayons.Alfred"),
            ("bartender", "Bartender", "com.surteesstudios.Bartender"),
            ("cleanmymac", "CleanMyMac", "com.macpaw.CleanMyMac"),
            ("cleanmymacx", "CleanMyMac X", "com.macpaw.CleanMyMac4"),
            ("appcleaner", "AppCleaner", "net.freemacsoft.AppCleaner"),
            ("app cleaner", "AppCleaner", "net.freemacsoft.AppCleaner"),
            ("ccleaner", "CCleaner", "com.piriform.ccleaner"),
            ("cleangenius", "CleanGenius", "com.tweakbit.cleangenius"),
            ("disk clean pro", "Disk Clean Pro", "com.cleverfiles.DiskCleanPro"),
            ("dr cleaner", "Dr. Cleaner", "com.trendmicro.DrCleaner"),
            ("gemini", "Gemini", "com.macpaw.Gemini2"),
            ("gemini 2", "Gemini 2", "com.macpaw.Gemini2"),
            ("app delete", "App Delete", "com.regeven.AppDelete"),
            ("appdelete", "App Delete", "com.regeven.AppDelete"),
            ("app uninstaller", "App Uninstaller", "com.nektony.App-Uninstaller"),
            ("appzapper", "AppZapper", "com.appzapper.AppZapper"),
            ("trashtaker", "TrashTaker", "com.fiplab.trashtaker"),
            ("clean my drive", "Clean My Drive", "com.systweak.MacCleanMyDrive"),
            ("stellar speedup", "Stellar Speedup Mac", "com.stellarinfo.speedupmac"),
            ("cleanup my system", "Cleanup My System", "com.systweak.cleanmysystem"),
            ("advanced mac cleaner", "Advanced Mac Cleaner", "com.pcvark.advancedmaccleaner"),
            ("super easy cleaner", "Super Easy Cleaner", "com.macmediaplayer.SuperEasyCleaner"),
            ("nektony app cleaner", "Nektony App Cleaner", "com.nektony.App-Cleaner-SIII"),
            ("osx uninstaller", "OSX Uninstaller", "com.osx-uninstaller"),
            ("cleanmydrive", "CleanMyDrive", "com.macpaw.CleanMyDrive2"),
            ("cleanmydrive 2", "CleanMyDrive 2", "com.macpaw.CleanMyDrive2"),
            ("macpaw", "MacPaw", "com.macpaw"),
            ("cleaner pro", "Cleaner Pro", "com.macpaw.CleanerPro"),
            ("gemini photos", "Gemini Photos", "com.macpaw.site.GeminiPhotos"),
            ("hider 2", "Hider 2", "com.macpaw.Hider2"),
            ("wallpaper wizard", "Wallpaper Wizard", "com.macpaw.WallpaperWizard2"),
            ("cisdem data recovery", "Cisdem Data Recovery", "com.cisdem.datarecovery"),
            ("transmit", "Transmit", "com.panic.Transmit"),
            ("istat", "iStat Menus", "com.bjango.istatmenus"),
            ("magnet", "Magnet", "com.crowdcafe.windowmagnet"),
            ("rectangle", "Rectangle", "com.knollsoft.Rectangle"),
            ("bettertouchtool", "BetterTouchTool", "com.hegenberg.BetterTouchTool"),
            ("karabiner", "Karabiner-Elements", "org.pqrs.Karabiner-Elements"),
            ("hazel", "Hazel", "com.noodlesoft.Hazel"),
            ("keyboard maestro", "Keyboard Maestro", "com.stairways.keyboardmaestro.engine"),
            ("little snitch", "Little Snitch", "at.obdev.LittleSnitch"),
            ("micro snitch", "Micro Snitch", "at.obdev.MicroSnitch"),
            ("setapp", "Setapp", "com.setapp.DesktopClient"),
            ("it.murus", "Murus", "it.murus"),
            ("the unarchiver", "The Unarchiver", "com.macpaw.site.theunarchiver"),
            ("keka", "Keka", "com.aone.keka"),
            ("macupdater", "MacUpdater", "com.corecode.MacUpdater"),
            ("logitech", "Logitech", "com.logitech"),
            ("logi options", "Logi Options+", "com.logi.cp-desktop"),
            ("logi options+", "Logi Options+", "com.logi.cp-desktop"),
            ("logitech options", "Logitech Options", "com.logitech.manager"),
            ("logitech control center", "Logitech Control Center", "com.logitech.control center"),
            ("logitech gaming software", "Logitech Gaming Software", "com.logitech.gaming"),
            ("lghub", "Logitech G HUB", "com.logi.ghub"),
            ("logitech g hub", "Logitech G HUB", "com.logi.ghub"),
            ("g hub", "Logitech G HUB", "com.logi.ghub"),
            ("logitech camera settings", "Logitech Camera Settings", "com.logitech.camera-settings"),
            ("logitech capture", "Logitech Capture", "com.logitech.capture"),
            ("logitech sync", "Logitech Sync", "com.logitech.sync"),
            ("logitech presentation", "Logitech Presentation", "com.logitech.presentation"),
            ("logi tune", "Logi Tune", "com.logitech.logitune"),
            ("logitech unifying", "Logitech Unifying Software", "com.logitech.unifying"),
            ("logitech firmware update", "Logitech Firmware Update Tool", "com.logitech.firmwareupdatetool"),
            ("garmin", "Garmin", "com.garmin"),
            ("garmin express", "Garmin Express", "com.garmin.GarminExpress"),
            ("garmin connect", "Garmin Connect", "com.garmin.Connect"),
            ("garmin basecamp", "Garmin BaseCamp", "com.garmin.BaseCamp"),
            ("garmin mapinstall", "Garmin MapInstall", "com.garmin.MapInstall"),
            ("garmin mapmanager", "Garmin MapManager", "com.garmin.MapManager"),
            ("garmin webupdater", "Garmin WebUpdater", "com.garmin.WebUpdater"),
            ("tomtom", "TomTom", "com.tomtom"),
            ("tomtom mydrive connect", "TomTom MyDrive Connect", "com.tomtom.MyDriveConnect"),
            ("tomtom home", "TomTom HOME", "com.tomtom.Home"),
            ("malwarebytes", "Malwarebytes", "com.malwarebytes.malwarebytes"),
            ("bitdefender", "Bitdefender", "com.bitdefender"),
            ("avast", "Avast", "com.avast"),
            ("avg", "AVG", "com.avg"),
            ("avira", "Avira", "com.avira"),
            ("com.avira", "Avira", "com.avira"),
            ("kaspersky", "Kaspersky", "com.kaspersky"),
            ("sophos", "Sophos", "com.sophos"),
            ("eset", "ESET", "com.eset"),
            ("norton", "Norton", "com.symantec"),
            ("mcafee", "McAfee", "com.mcafee"),
            ("clam", "ClamXAV", "com.codepoetry.clamxav"),
            ("backblaze", "Backblaze", "com.backblaze.Backblaze"),
            ("carbonite", "Carbonite", "com.carbonite"),
            ("crashplan", "CrashPlan", "com.code42.crashplan"),
            ("carbon copy", "Carbon Copy Cloner", "com.bombich.ccc"),
            ("superduper", "SuperDuper!", "com.shirt-pocket.SuperDuper"),
            ("chronosync", "ChronoSync", "com.econtechnologies.ChronoSync"),
            ("arq", "Arq", "com.haystacksoftware.Arq"),
            ("acronis", "Acronis", "com.acronis"),
            ("acronis true image", "Acronis True Image", "com.acronis.TrueImage"),
            ("acronis cyber protect", "Acronis Cyber Protect", "com.acronis.CyberProtect"),
            ("acronis cyber backup", "Acronis Cyber Backup", "com.acronis.CyberBackup"),
            ("acronis disk director", "Acronis Disk Director", "com.acronis.DiskDirector"),
            ("firefox", "Firefox", "org.mozilla.firefox"),
            ("brave", "Brave", "com.brave.Browser"),
            ("opera", "Opera", "com.operasoftware.Opera"),
            ("vivaldi", "Vivaldi", "com.vivaldi.Vivaldi"),
            ("arc", "Arc", "company.thebrowser.Browser"),
            ("tor browser", "Tor Browser", "org.torproject.torbrowser"),
            ("torbrowser", "Tor Browser", "org.torproject.torbrowser"),
            ("airmail", "Airmail", "it.bloop.airmail2"),
            ("spark", "Spark", "com.readdle.smartemail-Mac"),
            ("canary", "Canary Mail", "com.canarymail.mac"),
            ("mailmate", "MailMate", "com.freron.MailMate"),
            ("postbox", "Postbox", "com.postbox-inc.postbox"),
            ("thunderbird", "Thunderbird", "org.mozilla.thunderbird"),
            ("steam", "Steam", "com.valvesoftware.steam"),
            ("epic", "Epic Games", "com.epicgames.EpicGamesLauncher"),
            ("gog", "GOG Galaxy", "com.gog.galaxy"),
            ("battle.net", "Battle.net", "net.battle.app"),
            ("origin", "Origin", "com.ea.Origin"),
            ("uplay", "Ubisoft Connect", "com.ubisoft.upc"),
            ("postgres", "PostgreSQL", "org.postgresql"),
            ("sequel", "Sequel Pro", "com.sequelpro.SequelPro"),
            ("sequel ace", "Sequel Ace", "com.sequel-ace.sequel-ace"),
            ("tableplus", "TablePlus", "com.tinyapp.TablePlus"),
            ("mongodb", "MongoDB Compass", "com.mongodb.compass"),
            ("redis", "Redis", "io.redis.RedisInsight"),
            ("robo3t", "Robo 3T", "org.robomongo.Robo-3T"),
            ("warp", "Warp", "dev.warp.Warp-Stable"),
            ("kitty", "Kitty", "net.kovidgoyal.kitty"),
            ("alacritty", "Alacritty", "io.alacritty"),
            ("hyper", "Hyper", "co.zeit.hyper"),
            ("roam", "Roam Research", "com.roamresearch.desktop-app"),
            ("remnote", "RemNote", "com.remnote"),
            ("anki", "Anki", "net.ankiweb.dtop"),
            ("devonthink", "DEVONthink", "com.devon-technologies.think3"),
            ("tinderbox", "Tinderbox", "com.eastgate.Tinderbox-9"),
            ("mailchimp", "Mailchimp", "com.mailchimp"),
            ("sendinblue", "Sendinblue", "com.sendinblue"),
            ("speedtest", "Speedtest by Ookla", "com.ookla.speedtest"),
            ("com.ookla.speedtest", "Speedtest by Ookla", "com.ookla.speedtest"),
            ("loom", "Loom", "com.loom.desktop"),
            ("screenflow", "ScreenFlow", "net.telestream.screenflow9"),
            ("camtasia", "Camtasia", "com.techsmith.camtasia2021"),
            ("snagit", "Snagit", "com.techsmith.snagit2021"),
            ("capto", "Capto", "com.globaldelight.Capto"),
            ("kap", "Kap", "com.wulkano.kap"),
            ("nordvpn", "NordVPN", "com.nordvpn.osx"),
            ("expressvpn", "ExpressVPN", "com.expressvpn.ExpressVPN"),
            ("tunnelblick", "Tunnelblick", "net.tunnelblick.tunnelblick"),
            ("mullvad", "Mullvad VPN", "net.mullvad.vpn"),
            ("protonvpn", "ProtonVPN", "ch.protonvpn.mac"),
            ("viscosity", "Viscosity", "net.shinyfrog.viscosity"),
            ("cyberduck", "Cyberduck", "ch.sudo.cyberduck"),
            ("filezilla", "FileZilla", "de.filezilla"),
            ("forklift", "ForkLift", "com.binarynights.ForkLift-3"),
            ("gopro quik", "GoPro Quik", "com.gopro.quikdesktop"),
            ("go pro quik", "GoPro Quik", "com.gopro.quikdesktop"),
            ("goproquik", "GoPro Quik", "com.gopro.quikdesktop"),
            ("com.gopro", "GoPro Quik", "com.gopro.quikdesktop"),
            ("sony", "Sony Imaging Edge", "com.sony.ImagingEdge"),
            ("fujifilm", "FUJIFILM X RAW STUDIO", "com.fujifilm.denji.X_RAW_STUDIO"),
            ("canon", "Canon EOS Utility", "jp.co.canon.EOSUTILITY3"),
            ("nikon", "Nikon Transfer", "com.nikon.NikonTransfer2"),
            ("olympus", "Olympus Workspace", "jp.co.olympus.OLYMPUS-Workspace"),
            ("panasonic", "LUMIX Tether", "jp.co.panasonic.LUMIX_Tether"),
            ("leica", "Leica FOTOS", "com.leica-camera.fotos"),
            ("dji", "DJI Assistant", "com.dji.assistant"),
            ("capture one", "Capture One", "com.phaseone.captureone"),
            ("luminar", "Luminar", "com.skylum.luminar"),
            ("on1", "ON1 Photo RAW", "com.on1.photoraw"),
            ("dxo", "DxO PhotoLab", "com.dxo.photolab"),
            ("topaz", "Topaz Photo AI", "com.topazlabs.Topaz-Photo-AI"),
            ("tiktok", "TikTok", "com.zhiliaoapp.musically"),
            ("instagram", "Instagram", "com.instagram.www"),
            ("facebook", "Facebook", "com.facebook.archon"),
            ("twitter", "Twitter", "com.twitter.twitter-mac"),
            ("linkedin", "LinkedIn", "com.linkedin.LinkedIn"),
            ("buffer", "Buffer", "com.buffer.desktop"),
            ("hootsuite", "Hootsuite", "com.hootsuite.desktop"),
            ("canva", "Canva", "com.canva.CanvaDesktop"),
            ("prezi", "Prezi", "com.prezi.PreziDesktop"),
            ("fruity loops", "FL Studio", "com.image-line.flstudio"),
            ("cubase", "Cubase", "com.steinberg.cubase"),
            ("nuendo", "Nuendo", "com.steinberg.nuendo"),
            ("studio one", "Studio One", "com.presonus.studioone"),
            ("reason", "Reason", "se.propellerheads.reason"),
            ("bitwig", "Bitwig Studio", "com.bitwig.BitwigStudio"),
            ("mixxx", "Mixxx", "org.mixxx.mixxx"),
            ("serato", "Serato DJ", "com.serato.dj"),
            ("traktor", "Traktor", "com.native-instruments.Traktor"),
            ("rekordbox", "rekordbox", "com.pioneerdj.rekordbox"),
            ("autocad", "AutoCAD", "com.autodesk.autocad"),
            ("fusion360", "Fusion 360", "com.autodesk.mas.fusion360"),
            ("sketchup", "SketchUp", "com.sketchup.sketchup"),
            ("rhino", "Rhino", "com.mcneel.rhinoceros"),
            ("solidworks", "SOLIDWORKS", "com.solidworks"),
            ("revit", "Revit", "com.autodesk.revit"),
            ("archicad", "ArchiCAD", "com.graphisoft.archicad"),
            ("vectorworks", "Vectorworks", "net.vectorworks"),
            ("houdini", "Houdini", "com.sidefx.houdini"),
            ("unity", "Unity", "com.unity3d.UnityEditor"),
            ("unreal", "Unreal Engine", "com.epicgames.UnrealEngine"),
            ("godot", "Godot", "org.godotengine.Godot"),
            ("libreoffice", "LibreOffice", "org.libreoffice.script"),
            ("openoffice", "OpenOffice", "org.openoffice.script"),
            ("wps", "WPS Office", "com.kingsoft.wpsoffice.mac"),
            ("pdf expert", "PDF Expert", "com.readdle.PDFExpert-Mac"),
            ("pdfpen", "PDFpen", "com.smileonmymac.PDFpen"),
            ("nitro", "Nitro PDF", "com.nitropdf.nitropro"),
            ("foxit", "Foxit PDF", "com.foxit.PDF-Editor"),
            ("skim", "Skim", "net.sourceforge.skim-app.skim"),
            ("matlab", "MATLAB", "com.mathworks.matlab"),
            ("mathematica", "Mathematica", "com.wolfram.Mathematica"),
            ("maple", "Maple", "com.maplesoft.maple"),
            ("rstudio", "RStudio", "org.rstudio.RStudio"),
            ("jupyter", "Jupyter", "org.jupyter.jupyterlab-desktop"),
            ("spss", "SPSS", "com.ibm.spss.statistics"),
            ("stata", "Stata", "com.stata"),
            ("origin", "OriginLab", "com.originlab.origin"),
            ("zotero", "Zotero", "org.zotero.zotero"),
            ("mendeley", "Mendeley", "com.mendeley.desktop"),
            ("endnote", "EndNote", "com.ThomsonResearchSoft.EndNote"),
            ("trello", "Trello", "com.atlassian.trello"),
            ("asana", "Asana", "com.asana.desktop"),
            ("monday", "Monday.com", "com.monday"),
            ("clickup", "ClickUp", "com.clickup.desktop-app"),
            ("todoist", "Todoist", "com.todoist.mac.Todoist"),
            ("omnifocus", "OmniFocus", "com.omnigroup.OmniFocus3"),
            ("things", "Things", "com.culturedcode.ThingsMac"),
            ("fantastical", "Fantastical", "com.flexibits.fantastical2.mac"),
            ("quickbooks", "QuickBooks", "com.intuit.QuickBooks"),
            ("quicken", "Quicken", "com.quicken.Quicken"),
            ("moneymoney", "MoneyMoney", "com.moneymoney-app.retail"),
            ("banktivity", "Banktivity", "com.iggsoftware.Banktivity"),
            ("mint", "Mint", "com.intuit.mint"),
            ("vnc", "VNC Viewer", "com.realvnc.vncviewer"),
            ("screens", "Screens", "com.edovia.screens4.mac"),
            ("jump", "Jump Desktop", "com.jumpdesktop.jdmac"),
            ("chrome remote", "Chrome Remote Desktop", "com.google.chromeremotedesktop"),
            ("coconutbattery", "coconutBattery", "de.coconut-flavour.coconutBattery"),
            ("onyx", "OnyX", "com.titanium.OnyX"),
            ("etrecheck", "EtreCheck", "com.etresoft.EtreCheck"),
            ("geekbench", "Geekbench", "com.primatelabs.Geekbench"),
            ("intel power", "Intel Power Gadget", "com.intel.PowerGadget"),
            ("smcfancontrol", "smcFanControl", "com.eidac.smcFanControl2"),
            ("imazing", "iMazing", "com.DigiDNA.iMazing2Mac"),
            ("sensei", "Sensei", "ee.oskar.Sensei"),
            ("stats", "Stats", "eu.exelban.Stats"),
            ("elgato", "Elgato", "com.elgato"),
            ("stream deck", "Elgato Stream Deck", "com.elgato.StreamDeck"),
            ("streamdeck", "Elgato Stream Deck", "com.elgato.StreamDeck"),
            ("wave link", "Elgato Wave Link", "com.elgato.WaveLink"),
            ("wavelink", "Elgato Wave Link", "com.elgato.WaveLink"),
            ("4k capture utility", "Elgato 4K Capture Utility", "com.elgato.GameCapture"),
            ("game capture", "Elgato Game Capture", "com.elgato.GameCapture"),
            ("cam link", "Elgato Cam Link", "com.elgato.CamLink"),
            ("camlink", "Elgato Cam Link", "com.elgato.CamLink"),
            ("control center", "Elgato Control Center", "com.elgato.ControlCenter"),
            ("key light", "Elgato Key Light", "com.elgato.KeyLight"),
            ("keylight", "Elgato Key Light", "com.elgato.KeyLight"),
            ("epoccam", "EpocCam", "com.elgato.EpocCam"),
            ("wacom", "Wacom", "com.wacom"),
            ("wacom desktop center", "Wacom Desktop Center", "com.wacom.WacomDesktopCenter"),
            ("wacom tablet", "Wacom Tablet", "com.wacom.TabletDriver"),
            ("wacom driver", "Wacom Driver", "com.wacom.ProfessionalTablet"),
            ("wacom center", "Wacom Center", "com.wacom.WacomCenter"),
            ("bamboo", "Wacom Bamboo", "com.wacom.Bamboo"),
            ("intuos", "Wacom Intuos", "com.wacom.Intuos"),
            ("cintiq", "Wacom Cintiq", "com.wacom.Cintiq"),
            ("wacom experience", "Wacom Experience", "com.wacom.WacomExperience"),
            ("razer", "Razer", "com.razer"),
            ("razer synapse", "Razer Synapse", "com.razer.synapse"),
            ("razer chroma", "Razer Chroma", "com.razer.chroma"),
            ("razer cortex", "Razer Cortex", "com.razer.cortex"),
            ("corsair", "Corsair", "com.corsair"),
            ("icue", "Corsair iCUE", "com.corsair.cue"),
            ("corsair icue", "Corsair iCUE", "com.corsair.cue"),
            ("corsair link", "Corsair Link", "com.corsair.link"),
            ("steelseries", "SteelSeries", "com.steelseries"),
            ("steelseries gg", "SteelSeries GG", "com.steelseries.gg"),
            ("steelseries engine", "SteelSeries Engine", "com.steelseries.SteelSeriesEngine"),
            ("sonar", "SteelSeries Sonar", "com.steelseries.sonar"),
            ("rode", "Rode", "com.rode"),
            ("rode connect", "Rode Connect", "com.rode.connect"),
            ("rode central", "Rode Central", "com.rode.central"),
            ("rode reporter", "Rode Reporter", "com.rode.reporter"),
            ("blue sherpa", "Blue Sherpa", "com.bluemic.sherpa"),
            ("blue voice", "Blue Voice", "com.bluemic.voice"),
            ("focusrite", "Focusrite", "com.focusrite"),
            ("focusrite control", "Focusrite Control", "com.focusrite.control"),
            ("scarlett", "Focusrite Scarlett", "com.focusrite.scarlett"),
            ("presonus", "PreSonus", "com.presonus"),
            ("universal control", "PreSonus Universal Control", "com.presonus.universalcontrol"),
            ("native access", "Native Access", "com.native-instruments.NativeAccess"),
            ("komplete kontrol", "Komplete Kontrol", "com.native-instruments.KompleteKontrol"),
            ("maschine", "Maschine", "com.native-instruments.Maschine2"),
            ("traktor pro", "Traktor Pro", "com.native-instruments.Traktor"),
            ("reaktor", "Reaktor", "com.native-instruments.Reaktor6"),
            ("kontakt", "Kontakt", "com.native-instruments.Kontakt6"),
            ("massive", "Massive", "com.native-instruments.Massive"),
            ("battery", "Battery", "com.native-instruments.Battery4"),
            ("guitar rig", "Guitar Rig", "com.native-instruments.GuitarRig"),
            ("ableton link", "Ableton Link", "com.ableton.link"),
            ("avid link", "Avid Link", "com.avid.link"),
            ("media composer", "Media Composer", "com.avid.MediaComposer"),
            ("sibelius", "Sibelius", "com.avid.Sibelius"),
            ("pixelmator classic", "Pixelmator", "com.pixelmatorteam.pixelmator"),
            ("affinity", "Affinity", "com.seriflabs"),
            ("mindnode", "MindNode", "com.mindnode.MindNodeMac"),
            ("ithoughts", "iThoughts", "com.toketaware.ithoughtsx"),
            ("scrivener", "Scrivener", "com.literatureandlatte.scrivener3"),
            ("ia writer", "iA Writer", "pro.writer.mac"),
            ("marked", "Marked", "com.brettterpstra.marked2"),
            ("byword", "Byword", "com.metaclassy.byword"),
            ("typora", "Typora", "abnerworks.Typora"),
            ("macdown", "MacDown", "com.uranusjr.macdown"),
            ("tidal", "TIDAL", "com.aspiro.TIDAL"),
            ("deezer", "Deezer", "com.deezer.Deezer"),
            ("soundcloud", "SoundCloud", "com.soundcloud.desktop"),
            ("amazon music", "Amazon Music", "com.amazon.music"),
            ("youtube music", "YouTube Music", "com.google.YouTubeMusic"),
            ("bandcamp", "Bandcamp", "com.bandcamp.Bandcamp"),
            ("netflix", "Netflix", "com.netflix.Netflix"),
            ("disney", "Disney+", "com.disney.disneyplus"),
            ("hbo", "HBO Max", "com.hbo.hbomax"),
            ("amazon prime", "Prime Video", "com.amazon.avp"),
            ("youtube", "YouTube", "com.google.youtube"),
            ("vimeo", "Vimeo", "com.vimeo.desktop"),
            ("kodi", "Kodi", "tv.kodi.kodi"),
            ("mpv", "mpv", "io.mpv"),
            ("iina", "IINA", "com.colliderli.iina"),
            ("elmedia", "Elmedia Player", "com.eltima.elmedia-video-player"),
            ("gimp", "GIMP", "org.gimp.gimp"),
            ("inkscape", "Inkscape", "org.inkscape.Inkscape"),
            ("krita", "Krita", "org.krita"),
            ("darktable", "Darktable", "org.darktable"),
            ("rawtherapee", "RawTherapee", "com.rawtherapee.RawTherapee"),
            ("photoscape", "PhotoScape X", "com.mooii.psx"),
            ("pixlr", "Pixlr", "com.pixlr.desktop"),
            ("cleanshot", "CleanShot X", "pl.maketheweb.cleanshotx"),
            ("monosnap", "Monosnap", "com.monosnap.monosnap"),
            ("lightshot", "Lightshot", "com.skillbrains.lightshot"),
            ("skitch", "Skitch", "com.skitch.skitch"),
            ("xnapper", "Xnapper", "com.xnapper.app"),
            ("shottr", "Shottr", "cc.ffitch.shottr"),
            ("moom", "Moom", "com.manytricks.Moom"),
            ("divvy", "Divvy", "com.mizage.Divvy"),
            ("spectacle", "Spectacle", "com.divisiblebyzero.Spectacle"),
            ("sizeup", "SizeUp", "com.irradiatedsoftware.SizeUp"),
            ("amethyst", "Amethyst", "com.amethyst.Amethyst"),
            ("yabai", "yabai", "com.koekeishiya.yabai"),
            ("itsycal", "Itsycal", "com.mowglii.ItsycalApp"),
            ("menubar x", "MenubarX", "com.zrzz.menubarx"),
            ("vanilla", "Vanilla", "com.matthewpalmer.Vanilla"),
            ("hidden bar", "Hidden Bar", "com.dwarvesv.minimalbar"),
            ("dozer", "Dozer", "com.mortennn.Dozer"),
            ("paste", "Paste", "com.wiheads.paste"),
            ("copied", "Copied", "com.copiedapp.Copied"),
            ("clipy", "Clipy", "com.clipy-app.Clipy"),
            ("maccy", "Maccy", "org.p0deje.Maccy"),
            ("flycut", "Flycut", "com.generalarcade.flycut"),
            ("jumpcut", "Jumpcut", "net.sf.jumpcut"),
            ("raycast", "Raycast", "com.raycast.macos"),
            ("launchbar", "LaunchBar", "at.obdev.LaunchBar"),
            ("quicksilver", "Quicksilver", "com.blacktree.Quicksilver"),
            ("ubar", "uBar", "ca.brawer.ubar"),
            ("colorsnapper", "ColorSnapper", "com.koolesache.ColorSnapper2"),
            ("sip", "Sip", "io.sipapp.Sip-setapp"),
            ("pika", "Pika", "com.superhighfives.pika"),
            ("textexpander", "TextExpander", "com.smileonmymac.textexpander"),
            ("typinator", "Typinator", "com.macility.typinator7"),
            ("atext", "aText", "com.trankynam.aText"),
            ("rocket", "Rocket", "net.matthewpalmer.Rocket"),
            ("toggl", "Toggl Track", "com.toggl.toggldesktop.TogglDesktop"),
            ("timery", "Timery", "com.toggl.timery.mac"),
            ("rescuetime", "RescueTime", "com.rescuetime.RescueTime"),
            ("timing", "Timing", "info.eurocomp.Timing2"),
            ("harvest", "Harvest", "com.getharvest.harvestxapp"),
            ("clockify", "Clockify", "com.clockify.desktop"),
            ("freedom", "Freedom", "com.80pct.FreedomPlatform"),
            ("selfcontrol", "SelfControl", "org.eyebeam.SelfControl"),
            ("focus", "Focus", "BradJasper.focus"),
            ("be focused", "Be Focused", "com.denys-ievenko.BeFocusedPro"),
            ("forest", "Forest", "com.seekrtech.forest"),
            ("serene", "Serene", "com.serene"),
            ("wireshark", "Wireshark", "org.wireshark.Wireshark"),
            ("charles", "Charles", "com.xk72.charles"),
            ("proxyman", "Proxyman", "com.proxyman.NSProxy"),
            ("paw", "Paw", "com.luckymarmot.Paw"),
            ("rapid api", "RapidAPI", "com.rapidapi.RapidAPI"),
            ("httpie", "HTTPie", "io.httpie.desktop"),
            ("hoppscotch", "Hoppscotch", "io.hoppscotch.desktop"),
            ("bruno", "Bruno", "com.usebruno.app"),
            ("gitbox", "Gitbox", "com.oleganza.gitbox"),
            ("github desktop", "GitHub Desktop", "com.github.GitHubClient"),
            ("gitlab", "GitLab", "com.gitlab.GitLab"),
            ("gitkraken", "GitKraken", "com.axosoft.gitkraken"),
            ("sublime merge", "Sublime Merge", "com.sublimemerge"),
            ("obsidian md", "Obsidian", "md.obsidian"),
            ("bear writer", "Bear", "net.shinyfrog.bear"),
            ("notion md", "Notion", "notion.id"),
            ("quiver", "Quiver", "com.happenapps.Quiver"),
            ("notable", "Notable", "md.notable.notable"),
            ("zettlr", "Zettlr", "com.zettlr.app"),
            ("reeder", "Reeder", "com.reederapp.5.macOS"),
            ("netnewswire", "NetNewsWire", "com.ranchero.NetNewsWire-Evergreen"),
            ("feedly", "Feedly", "com.devhd.feedly"),
            ("readkit", "ReadKit", "com.webinhq.ReadKit"),
            ("carrot", "CARROT Weather", "com.grailr.CARROTweather"),
            ("dark sky", "Dark Sky", "com.jackadam.darksky"),
            ("deepl", "DeepL", "com.linguee.DeepLProMac"),
            ("google translate", "Google Translate", "com.google.GoogleTranslate"),
            ("kindle", "Kindle", "com.amazon.Kindle"),
            ("calibre", "Calibre", "net.kovidgoyal.calibre"),
            ("bookends", "Bookends", "com.sonnysoftware.bookends"),
            ("omnigraffle", "OmniGraffle", "com.omnigroup.OmniGraffle7"),
            ("lucidchart", "Lucidchart", "com.lucidchart.lucidchart"),
            ("draw.io", "draw.io", "com.jgraph.drawio.desktop"),
            ("miro", "Miro", "com.realtimeboard.miro"),
            ("whimsical", "Whimsical", "com.whimsical.app"),
            ("messenger", "Messenger", "com.facebook.messenger"),
            ("viber", "Viber", "com.viber.osx"),
            ("wechat", "WeChat", "com.tencent.xinWeChat"),
            ("line", "LINE", "jp.naver.line.mac"),
            ("forklift", "ForkLift", "com.binarynights.ForkLift-3"),
            ("pathfinder", "Path Finder", "com.cocoatech.PathFinder"),
            ("commander one", "Commander One", "com.eltima.cmd1"),
            ("totalfinder", "TotalFinder", "com.binaryage.totalfinder"),
            ("xtrafinder", "XtraFinder", "com.trankynam.XtraFinder"),
            ("stratospherix", "Stratospherix", "com.stratospherix"),
            ("file browser", "File Browser", "com.stratospherix.filebrowsermac"),
            ("filebrowser", "File Browser", "com.stratospherix.filebrowsermac"),
            ("file browser business", "File Browser Business", "com.stratospherix.filebrowserbusiness"),
            ("file browser go", "File Browser Go", "com.stratospherix.filebrowsergo"),
            ("pdf viewer", "PDF Viewer", "com.stratospherix.pdfviewer"),
            ("pdf expert", "PDF Expert by Stratospherix", "com.stratospherix.pdfexpert"),
            ("daisy disk", "DaisyDisk", "com.daisydiskapp.DaisyDiskStandalone"),
            ("disk inventory x", "Disk Inventory X", "com.derlien.diskinventoryx"),
            ("grandperspective", "GrandPerspective", "net.sourceforge.grandperspectiv"),
            ("driveDx", "DriveDx", "com.binaryfruit.DriveDx"),
            ("disk drill", "Disk Drill", "com.508softworks.Disk-Drill"),
            ("menu meters", "MenuMeters", "com.ragingmenace.MenuMeters"),
            ("monit", "Monit", "com.monitorit.monit"),
            ("fontbase", "FontBase", "com.fontbase.app"),
            ("skyfonts", "SkyFonts", "com.monotype.skyfonts"),
            ("rightfont", "RightFont", "com.rightfontapp.RightFont"),
            ("discord overlay", "Discord", "com.hnc.Discord"),
            ("openemu", "OpenEmu", "org.openemu.OpenEmu"),
            ("dolphin", "Dolphin Emulator", "org.dolphin-emu.dolphin"),
            ("retroarch", "RetroArch", "com.libretro.RetroArch"),
            ("sequel pro", "Sequel Pro", "com.sequelpro.SequelPro"),
            ("navicat", "Navicat", "com.premnirmal.navicat"),
            ("pgadmin", "pgAdmin", "org.postgresql.pgadmin"),
            ("dbeaver", "DBeaver", "org.jkiss.dbeaver.core.product"),
            ("redis desktop", "Redis Desktop Manager", "io.redisdesktop.RedisDesktopManager"),
            ("studio3t", "Studio 3T", "com.3T.mongochef"),
            ("jupyter notebook", "Jupyter Notebook", "org.jupyter.notebook"),
            ("anaconda", "Anaconda Navigator", "com.anaconda.Navigator"),
            ("pycharm ce", "PyCharm CE", "com.jetbrains.pycharm.ce"),
            ("intellij ce", "IntelliJ IDEA CE", "com.jetbrains.intellij.ce"),
            ("izotope", "iZotope", "com.izotope"),
            ("waves", "Waves", "com.waves"),
            ("universal audio", "Universal Audio", "com.uaudio"),
            ("native instruments", "Native Instruments", "com.native-instruments"),
            ("arturia", "Arturia", "com.arturia"),
            ("steinberg", "Steinberg", "com.steinberg"),
            ("resilio", "Resilio Sync", "com.resilio.Sync"),
            ("syncthing", "Syncthing", "net.syncthing.syncthing-macos"),
            ("goodsync", "GoodSync", "com.siber.goodsync"),
            ("syncmate", "SyncMate", "com.eltima.SyncMate"),
            ("mamp", "MAMP", "de.appsolut.MAMP"),
            ("xampp", "XAMPP", "org.xampp"),
            ("local", "Local by Flywheel", "com.getflywheel.local"),
            ("serverpilot", "ServerPilot", "com.serverpilot"),
            ("nginx", "Nginx", "org.nginx"),
            ("apache", "Apache", "org.apache"),
            ("little flocker", "Little Flocker", "at.obdev.LittleFlocker"),
            ("cheatsheet", "CheatSheet", "com.mediaatelier.CheatSheet"),
            ("popclip", "PopClip", "com.pilotmoon.popclip"),
            ("default folder", "Default Folder X", "com.stclairsoft.DefaultFolderX5"),
            ("pathsnagger", "Path Snagger", "com.ranchero.pathsnagger"),
            ("name mangler", "Name Mangler", "com.manytricks.NameMangler"),
            ("drop zone", "DropZone", "aptonic.dropzone3"),
            ("hookshot", "Hookshot", "com.hookshot"),
            ("contexts", "Contexts", "com.contextsformac.Contexts"),
            ("witch", "Witch", "com.manytricks.Witch"),
            ("commandQ", "CommandQ", "com.clickontyler.commandq"),
            ("nucleo", "Nucleo", "co.ambercreative.nucleo"),
            ("iconjar", "IconJar", "com.iconjar.app"),
            ("noun project", "Noun Project", "com.thenounproject.mac"),
            ("principle", "Principle", "com.danielhooper.principle"),
            ("flinto", "Flinto", "com.flinto.flinto"),
            ("origami", "Origami Studio", "com.facebook.OrigamiStudio"),
            ("haiku animator", "Haiku Animator", "com.haiku.haiku"),
            ("cavalry", "Cavalry", "com.scenery.cavalry"),
            ("waterfox", "Waterfox", "net.waterfox.waterfox"),
            ("pale moon", "Pale Moon", "org.palemoon.browser"),
            ("min", "Min Browser", "com.minbrowser.min"),
            ("sidekick", "Sidekick", "com.pushplaylabs.sidekick"),
            ("browserosaurus", "Browserosaurus", "com.browserosaurus"),
            ("mailmate", "MailMate", "com.freron.MailMate"),
            ("mailplane", "Mailplane", "com.mailplaneapp.Mailplane"),
            ("mimestream", "Mimestream", "com.mimestream.Mimestream"),
            ("polymail", "Polymail", "com.polymail.desktop"),
            ("tweetbot", "Tweetbot", "com.tapbots.Tweetbot3Mac"),
            ("twitterrific", "Twitterrific", "com.iconfactory.Twitterrific"),
            ("feather", "Feather", "com.featherformac.Feather"),
            ("acta", "Acta", "com.auscomp.acta5"),
            ("2do", "2Do", "com.guidedways.2Do"),
            ("busycal", "BusyCal", "com.busymac.busycal3"),
            ("busycontacts", "BusyContacts", "com.busymac.busycontacts"),
            ("cardhop", "Cardhop", "com.flexibits.cardhop.mac"),
            ("papers", "Papers", "com.mekentosj.papers3"),
            ("bookends", "Bookends", "com.sonnysoftware.bookends"),
            ("sente", "Sente", "com.thirdstreetsoftware.sente6"),
            ("refme", "RefMe", "com.refme"),
            ("xmind", "XMind", "net.xmind.vana"),
            ("simplemind", "SimpleMind", "com.modelmakertools.simplemindmac"),
            ("conceptdraw", "ConceptDraw", "com.conceptdraw"),
            ("cacoo", "Cacoo", "com.cacoo"),
            ("taskpaper", "TaskPaper", "com.hogbaysoftware.TaskPaper3"),
            ("org mode", "OrgMode", "com.orgmode"),
            ("recordit", "Recordit", "com.recordit"),
            ("gifox", "Gifox", "com.arik.gifox"),
            ("licecap", "LICEcap", "com.cockos.licecap"),
            ("giphy capture", "GIPHY Capture", "com.giphy.gifcapture"),
            ("cloudapp", "CloudApp", "com.linebreak.CloudAppMacOSX"),
            ("droplr", "Droplr", "com.droplr.droplrmac"),
            ("betterzip", "BetterZip", "com.macitbetter.betterzip"),
            ("stuffit", "StuffIt Expander", "com.stuffit.StuffItExpander"),
            ("izip", "iZip", "com.isotope244.iZip"),
            ("winzip", "WinZip", "com.winzip.mac.winzip"),
            ("zipeg", "Zipeg", "com.zipeg.Zipeg"),
            ("ghostery", "Ghostery", "com.ghostery.ghost"),
            ("adguard", "AdGuard", "com.adguard.mac.adguard"),
            ("1blocker", "1Blocker", "com.salavat.1Blocker"),
            ("blockblock", "BlockBlock", "com.objective-see.blockblock"),
            ("lulu", "LuLu", "com.objective-see.lulu"),
            ("knockknock", "KnockKnock", "com.objective-see.knockknock"),
            ("oversight", "OverSight", "com.objective-see.oversight"),
            ("ransomwhere", "RansomWhere", "com.objective-see.ransomwhere"),
            ("netiquette", "Netiquette", "com.objective-see.netiquette"),
            ("do not disturb", "Do Not Disturb", "com.objective-see.dnd"),
            ("tg pro", "TG Pro", "com.tunabellysoftware.tgpro"),
            ("macs fan control", "Macs Fan Control", "com.crystalidea.macsfancontrol"),
            ("app tamer", "App Tamer", "com.stclairsoft.AppTamer"),
            ("endurance", "Endurance", "com.magneticbear.endurance"),
            ("sloth", "Sloth", "org.sveinbjorn.Sloth"),
            ("lingon", "Lingon X", "com.peterborgapps.LingonX"),
            ("launchcontrol", "LaunchControl", "com.soma-zone.LaunchControl"),
            ("audio hijack", "Audio Hijack", "com.rogueamoeba.AudioHijack3"),
            ("loopback", "Loopback", "com.rogueamoeba.loopback"),
            ("soundsource", "SoundSource", "com.rogueamoeba.soundsource"),
            ("farrago", "Farrago", "com.rogueamoeba.Farrago"),
            ("fission", "Fission", "com.rogueamoeba.Fission"),
            ("piezo", "Piezo", "com.rogueamoeba.Piezo"),
            ("permute", "Permute", "com.charliemonroe.Permute"),
            ("downie", "Downie", "com.charliemonroe.Downie"),
            ("airy", "Airy", "com.eltima.Airy"),
            ("iflicks", "iFlicks", "com.iflicksapp.iflicks3"),
            ("subler", "Subler", "org.subler.Subler"),
            ("videoproc", "VideoProc", "com.digiarty.videoproc"),
            ("forecast", "Forecast", "com.overcast.ForecastMac"),
            ("podcast chapters", "Podcast Chapters", "com.chaptersapp.PodcastChapters"),
            ("ferrite", "Ferrite", "com.wooji-juice.ferrite"),
            ("shopify", "Shopify", "com.shopify"),
            ("stripe", "Stripe", "com.stripe"),
            ("chanty", "Chanty", "com.chanty.desktop"),
            ("flock", "Flock", "com.flock"),
            ("mattermost", "Mattermost", "com.mattermost.desktop"),
            ("rocket chat", "Rocket.Chat", "chat.rocket.electron"),
            ("zulip", "Zulip", "org.zulip.Zulip"),
            ("wire", "Wire", "com.wearezeta.zclient.mac"),
            ("tresorit", "Tresorit", "com.tresorit.mac"),
            ("seafile", "Seafile", "com.seafile.seafile-client"),
            ("pcloud", "pCloud", "com.pcloud.pcloud"),
            ("internxt", "Internxt Drive", "com.internxt.drive"),
            ("salesforce", "Salesforce", "com.salesforce"),
            ("hubspot", "HubSpot", "com.hubspot"),
            ("zendesk", "Zendesk", "com.zendesk"),
            ("freshdesk", "Freshdesk", "com.freshdesk"),
            ("intercom", "Intercom", "io.intercom.macos"),
            ("ubiquiti", "UniFi Network", "com.ubnt.UniFi-Discover"),
            ("unifi", "UniFi Network", "com.ubnt.UniFi-Discover"),
            ("synology", "Synology", "com.synology"),
            ("synology drive", "Synology Drive", "com.synology.CloudStationUI"),
            ("synology assistant", "Synology Assistant", "com.synology.DSAssistant"),
            ("synology photos", "Synology Photos", "com.synology.SynologyPhotos"),
            ("synology note station", "Synology Note Station", "com.synology.NoteStation"),
            ("synology chat", "Synology Chat", "com.synology.Chat"),
            ("ds file", "DS file", "com.synology.DSfile"),
            ("ds get", "DS get", "com.synology.DSdownload"),
            ("ds photo", "DS photo", "com.synology.DSphoto"),
            ("ds audio", "DS audio", "com.synology.DSaudio"),
            ("ds video", "DS video", "com.synology.DSvideo"),
            ("ds cloud", "DS cloud", "com.synology.DScloud"),
            ("ds cam", "DS cam", "com.synology.DScam"),
            ("surveillance station", "Surveillance Station", "com.synology.SurveillanceStation"),
            ("qnap", "QNAP", "com.qnap"),
            ("qfinder", "Qfinder Pro", "com.qnap.qfinder"),
            ("qsync", "Qsync", "com.qnap.qsync"),
            ("qfile", "Qfile", "com.qnap.qfile"),
            ("qphoto", "Qphoto", "com.qnap.qphoto"),
            ("qmusic", "Qmusic", "com.qnap.qmusic"),
            ("qvideo", "Qvideo", "com.qnap.qvideo"),
            ("qget", "Qget", "com.qnap.qget"),
            ("qmanager", "Qmanager", "com.qnap.qmanager"),
            ("qnapcloud", "myQNAPcloud Connect", "com.qnap.myqnapcloudconnect"),
            ("netbak", "NetBak Replicator", "com.qnap.NetBakReplicator"),
            ("terramaster", "TerraMaster", "com.terra-master"),
            ("tos", "TOS Desktop", "com.terra-master.TOS"),
            ("tnas", "TNAS Desktop", "com.terra-master.TNAS"),
            ("tnas mobile", "TNAS mobile", "com.terra-master.TNASmobile"),
            ("tbackup", "TBackup", "com.terra-master.TBackup"),
            ("ugreen", "UGREEN", "com.ugreen"),
            ("ugreen sync", "UGREEN Sync", "com.ugreen.sync"),
            ("ugos", "UGOS", "com.ugreen.ugos"),
            ("asustor", "Asustor", "com.asustor"),
            ("acc", "ASUSTOR Control Center", "com.asustor.acc"),
            ("aec", "ASUSTOR EZ Connect", "com.asustor.aec"),
            ("aidata", "AiData", "com.asustor.aidata"),
            ("aimaster", "AiMaster", "com.asustor.aimaster"),
            ("aiphoto", "AiPhotos", "com.asustor.aiphoto"),
            ("aimusic", "AiMusic", "com.asustor.aimusic"),
            ("aivideo", "AiVideo", "com.asustor.aivideo"),
            ("aidownload", "AiDownload", "com.asustor.aidownload"),
            ("com.wdc", "Western Digital", "com.wdc"),
            ("western digital", "Western Digital", "com.wdc"),
            ("wd", "Western Digital", "com.wdc"),
            ("wd my cloud", "WD My Cloud", "com.wdc.mycloud"),
            ("wd discovery", "WD Discovery", "com.wdc.WDDiscovery"),
            ("wd sync", "WD Sync", "com.wdc.WDSync"),
            ("wd backup", "WD Backup", "com.wdc.WDBackup"),
            ("wd security", "WD Security", "com.wdc.WDSecurity"),
            ("wd drive utilities", "WD Drive Utilities", "com.wdc.driveUtilities"),
            ("wd access", "WD Access", "com.wdc.WDAccess"),
            ("wd smartware", "WD SmartWare", "com.wdc.WDSmartWare"),
            ("seagate", "Seagate", "com.seagate"),
            ("seagate toolkit", "Seagate Toolkit", "com.seagate.toolkit"),
            ("seagate dashboard", "Seagate Dashboard", "com.seagate.dashboard"),
            ("seagate nas", "Seagate NAS", "com.seagate.nas"),
            ("lyve", "Seagate Lyve", "com.seagate.lyve"),
            ("buffalo", "Buffalo", "com.buffalo"),
            ("nas navigator", "NAS Navigator", "com.buffalo.nasnavigator"),
            ("buffalo toolbox", "Buffalo Toolbox", "com.buffalo.toolbox"),
            ("netgear", "Netgear", "com.netgear"),
            ("readynas", "ReadyNAS", "com.netgear.readynas"),
            ("readycloud", "ReadyCloud", "com.netgear.readycloud"),
            ("netgear insight", "Netgear Insight", "com.netgear.insight"),
            ("truenas", "TrueNAS", "org.truenas"),
            ("freenas", "FreeNAS", "org.freenas"),
            ("unraid", "Unraid", "net.lime-technology.unraid"),
            ("openmediavault", "OpenMediaVault", "org.openmediavault"),
            ("omv", "OpenMediaVault", "org.openmediavault"),
        ]
        
        for (pattern, appName, bundleID) in patterns {
            if nameLower.contains(pattern) {
                return CachedResult(
                    appName: appName,
                    bundleID: bundleID,
                    timestamp: Date(),
                    confidence: .medium
                )
            }
        }
        
        return nil
    }
    
    private func matchKnownPatterns(_ name: String) -> CachedResult? {
        let nameLower = name.lowercased()
        
        if nameLower.hasSuffix("helper") || nameLower.hasSuffix("agent") {
            let baseName = nameLower
                .replacingOccurrences(of: "helper", with: "")
                .replacingOccurrences(of: "agent", with: "")
                .trimmingCharacters(in: .whitespaces)
            
            if !baseName.isEmpty {
                return CachedResult(
                    appName: baseName.capitalized,
                    bundleID: nil,
                    timestamp: Date(),
                    confidence: .low
                )
            }
        }
        
        return nil
    }
    
    // MARK: - Helpers
    
    private func cleanItemName(_ name: String) -> String {
        var cleaned = name
            .lowercased()
            .replacingOccurrences(of: ".plist", with: "")
            .replacingOccurrences(of: ".app", with: "")
            .replacingOccurrences(of: ".framework", with: "")
        
        let prefixes = ["com.", "org.", "net.", "io.", "app."]
        for prefix in prefixes {
            if cleaned.hasPrefix(prefix) {
                cleaned = String(cleaned.dropFirst(prefix.count))
            }
        }
        
        return cleaned
    }
    
    private func cacheResult(for name: String, result: CachedResult) {
        cache[name] = result
    }
    
    // MARK: - Cache Management
    
    func clearExpiredCache() {
        cache = cache.filter { !$0.value.isExpired }
    }
    
    func clearAllCache() {
        cache.removeAll()
    }
}
